---
server_script: server/index.js
web_server_user: www-data
backup_host: vifta.strekmann.no
backup_user: backup-{{ project_user }}
backup_port: 2024
backup_uri: ssh://{{ backup_user }}@{{ backup_host }}:{{ backup_port }}
dhparam_path: /etc/ssl/certs/dhparam.pem
server_secret: "{{ vault_server_secret }}"
facebook:
    client_id: "{{ vault_facebook_client_id }}"
    client_secret: "{{ vault_facebook_client_secret }}"
google:
    client_id: "{{ vault_google_client_id }}"
    client_secret: "{{ vault_google_client_secret }}"
twitter:
    client_id: "{{ vault_twitter_client_id }}"
    client_secret: "{{ vault_twitter_client_secret }}"
smtp:
    host: "{{ vault.smtp.host }}"
    port: "{{ vault.smtp.port }}"
    auth:
        user: "{{ vault.smtp.auth.user }}"
        pass: "{{ vault.smtp.auth.pass }}"
    noreply_address: "{{ vault.smtp.noreply_address }}"
