---
  - name: Build node project in virtual environment
    hosts: all
    vars:
      - repo: /repo
        build_dir: /srv/{{ project_name }}
        cache_dir: /cache

    tasks:
      - name: Install http transport for apt
        apt: name=apt-transport-https state=present

      - name: Setup nodesource repository
        apt_repository: repo="deb http://deb.nodesource.com/node_6.x jessie main" state=present

      - name: Add nodesource key
        apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present

      - name: Setup Yarn repository
        apt_repository: repo="deb https://dl.yarnpkg.com/debian/ stable main" state=present

      - name: Add Yarn key
        apt_key: url=https://dl.yarnpkg.com/debian/pubkey.gpg state=present

      - name: Install dependencies
        apt: name={{ item }} state=present update_cache=yes
        with_items:
          - build-essential
          - yarn
          - git
          - nodejs

      - name: Clone repository
        git:
          repo: "{{ repo }}"
          dest: "{{ build_dir }}"

      - name: Install project dependencies
        command: yarn install --no-progress --silent --production --cache-folder={{ cache_dir }}
        args:
          chdir: "{{ build_dir }}"

      - name: Sync back node_modules
        synchronize:
          mode: pull
          src: "{{ build_dir }}/node_modules/"
          dest: ../dist/node_modules
